In [18]:
folder_path="C:\\Users\\KIIT\\Desktop\\Country Dashboard\\artifacts\\05_25_2026_06_33_18\\data_ingestion\\raw_data"

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [19]:
df=pd.read_csv(f"{folder_path}\\air_pollution_raw.csv")
df.head()

  Country Country_Code  Year  Value      Indicator
0   India          IND  2025    NaN  air_pollution
1   India          IND  2024    NaN  air_pollution
2   India          IND  2023    NaN  air_pollution
3   India          IND  2022    NaN  air_pollution
4   India          IND  2021    NaN  air_pollution

In [24]:
df.isna().sum()

Country          0
Country_Code     0
Year             0
Value           35
Indicator        0
dtype: int64

In [26]:
df

   Country Country_Code  Year  Value      Indicator
0    India          IND  2025    NaN  air_pollution
1    India          IND  2024    NaN  air_pollution
2    India          IND  2023    NaN  air_pollution
3    India          IND  2022    NaN  air_pollution
4    India          IND  2021    NaN  air_pollution
..     ...          ...   ...    ...            ...
61   India          IND  1964    NaN  air_pollution
62   India          IND  1963    NaN  air_pollution
63   India          IND  1962    NaN  air_pollution
64   India          IND  1961    NaN  air_pollution
65   India          IND  1960    NaN  air_pollution

[66 rows x 5 columns]